export const GET_PRODUCT_DETAIL: string = 'GET_PRODUCT_DETAIL'
export const FILTER_LIST_PRODUCT_IN_FILTER_PAGE: string = 'FILTER_LIST_PRODUCT_IN_FILTER_PAGE'
export const GET_FAVOURITE_PRODUCTS: string = 'GET_FAVOURITE_PRODUCTS'