import localFont from "next/font/local";
import { Suspense } from 'react'
import { Inter } from 'next/font/google'
import Footer from "@/components/Footer/Footer";
import StoreProvider from '@/Redux/StoreProvider'
import Loading from './loading'
import Header from '@/app/tools/components/Header/Header'
import LoginPopup from '@/app/tools/components/LoginPopup/LoginPopup'
import SignUpPopup from '@/app/tools/components/SignUpPopup/SignUpPopup'

import './globals.css'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Homefy",
  description: "Generated by Zoe",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:wght@300&family=Hind+Mysuru:wght@300;400;500;600;700&family=M+PLUS+Code+Latin:wght@100..700&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet" />
      </head>
      <body style={{ margin: 0, padding: 0 }}>
        <StoreProvider>
          <div >
            <Header />
            <div>
              <Suspense fallback={<Loading />}>
                {children}
              </Suspense>
            </div>
            <Footer />
            <LoginPopup />
            <SignUpPopup />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
